[package]
name = "progenitor"
version = "0.0.0"
edition = "2018"
license = "MPL-2.0"
repository = "https://github.com/oxidecomputer/progenitor.git"
description = "An OpenAPI client generator"

[dependencies]
anyhow = "1"
getopts = "0.2"
serde = { version = "1", features = [ "derive" ]}
serde_json = "1"
serde_yaml = "^0.8.17"
titlecase = "1.0"
openapiv3 = "0.5"
