[package]
name = "github-api-client"
description = "A fully generated & opinionated API client for the GitHub API."
version = "0.1.0"
documentation = "https://docs.rs/github-api-client/"
repository = "https://github.com/oxidecomputer/github-api-client"
readme = "README.md"
edition = "2018"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
dirs = { version = "^3.0.2", optional = true }
http = "^0.2.4"
jsonwebtoken = "7"
percent-encoding = "2.1"
reqwest = { version = "0.11", features = ["json"] }
schemars = { version = "0.8", features = ["chrono", "uuid"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
# enable etag-based http_cache functionality
httpcache = ["dirs"]
