[package]
name = "github"
version = "0.0.0"
edition = "2018"

[dependencies]
anyhow = "1"
chrono = "0.4"
percent-encoding = "2.1"
reqwest = { version = "0.11", features = ["json"] }
schemars = { version = "0.8", features = ["chrono", "uuid"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"