[package]
name = "github-api-client"
description = "A fully generated & opinionated API client for the GitHub API."
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
percent-encoding = "2.1"
reqwest = { version = "0.11", features = ["json"] }
schemars = { version = "0.8", features = ["chrono", "uuid"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"